name: Install Konveyor
description: |
  Install Konveyor Operator.
inputs: 
  bundle-image:
    description: "image url for operator bundle container image"
    required: true
  tackle-cr:
    description: "tackle custom resource string"
    required: false
    default: 0
runs:
  using: "composite"
  steps:
  # TODO(djzager): Need to figure out overriding operator image
  # or maybe just installing manager via kustomize.
  - name: Install Konveyor
    run: |
      export OPERATOR_BUNDLE_IMAGE="${{ inputs.bundle-image }}"
      export TACKLE_CR="${{ inputs.tackle-cr }}"
      make install-konveyor
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
