name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semantic version of the release (e.g. v1.2.3)'
        required: true
      branch:
        description: 'The branch to create the release from (defaults to main)'
        required: false
        default: 'main'

jobs:
  # TODO(djzager): This is where we would want to do some integration testing
  # test:
  #   ...
  # might consider creating "rc" releases, building and testing those before
  # publishing a release.
  release-components:
    strategy:
      matrix:
        repository:
          - konveyor/tackle2-hub
          - konveyor/tackle2-ui
          - konveyor/tackle2-addon
          - konveyor/tackle2-addon-windup
          - konveyor/tackle2-operator
    uses: konveyor/release-tools/.github/workflows/create-release.yml@main
    with:
      version: ${{ inputs.version }}
      repository: ${{ matrix.repository }}
      ref: ${{ inputs.branch }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}
      # TODO(djzager) Next we'll need to force the multi-arch build steps to run

  wait-for-images:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - konveyor/tackle2-hub
          - konveyor/tackle2-ui
          - konveyor/tackle2-addon
          - konveyor/tackle2-addon-windup
          - konveyor/tackle2-operator
    steps:
      - name: Pull the image
        run: |
          #!/bin/bash
          while ! docker pull quay.io/${{ matrix.image }}:${{ inputs.version }} &> /dev/null; do
              sleep 3m
          done
          docker image inspect quay.io/${{ matrix.image }}:${{ inputs.version }}
