name: PR Checks

on:
  pull_request:
    branches:
      - main
      - 'release-*.*'

env:
  IMG: ttl.sh/konveyor-operator-${{ github.sha }}:1h
  BUNDLE_IMG: ttl.sh/konveyor-operator-bundle-${{ github.sha }}:1h

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
    - uses: konveyor/release-tools/cmd/verify-pr@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-operator:
    needs: check-title
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make docker-build docker-push

  build-bundle:
    needs: build-operator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make bundle bundle-build bundle-push

  operator-install:
    needs: build-bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make start-minikube
    - run: OPERATOR_BUNDLE_IMAGE="${BUNDLE_IMG}" make install-tackle
