name: PR Checks

on:
  pull_request:
    branches:
      - main
      - 'release-*.*'


jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
    - uses: konveyor/release-tools/cmd/verify-pr@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-operator:
    needs: check-title
    runs-on: ubuntu-latest
    env:
      IMG: ttl.sh/konveyor-operator-${{ github.sha }}:1h
    steps:
    - uses: actions/checkout@v3
    - run: make docker-build docker-push

  run-ci:
    needs: build-operator
    uses: konveyor/ci/.github/workflows/global-ci-bundle.yml@main
    with:
      operator: ttl.sh/konveyor-operator-${{ github.sha }}:1h
